/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestTemplateAddonUserSystemProxy;

import javassist.*;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.instrument.Instrumentation;
import java.security.ProtectionDomain;
import java.util.Objects;

public class RestTemplateRewrite {
    public static void premain(String agentArgs, Instrumentation instrumentation) {
        instrumentation.addTransformer(new ClassFileTransformer() {
            @Override
            public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
                if (className.equals("org/springframework/web/client/RestTemplate")) {
                    ClassPool classPool = ClassPool.getDefault();
                    ByteArrayInputStream stream = new ByteArrayInputStream(classfileBuffer);
                    try {
                        CtClass ctClass = classPool.makeClass(stream);

                        CtConstructor[] constructors = ctClass.getDeclaredConstructors();
                        for (CtConstructor ctConstructor : constructors) {
                            try (BufferedReader br = new BufferedReader(
                                    new InputStreamReader(
                                            Objects.requireNonNull(ClassLoader.getSystemResourceAsStream(
                                                    "bodySource.txt"))))) {
                                StringBuilder sb = new StringBuilder();
                                while (br.ready()) {
                                    sb.append(br.readLine());
                                }

                                ctConstructor.insertBeforeBody(
                                        sb.toString()
                                );
                            }
                        }
                        CtMethod method = ctClass.getDeclaredMethod("setRequestFactory");
                        try (BufferedReader br = new BufferedReader(
                                new InputStreamReader(
                                        Objects.requireNonNull(ClassLoader.getSystemResourceAsStream(
                                                "reWriteSetRequestFactory.txt"))))) {
                            StringBuilder sb = new StringBuilder();
                            while (br.ready()) {
                                sb.append(br.readLine());
                            }
                            method.setBody(sb.toString());
                        }

                        return ctClass.toBytecode();
                    } catch (IOException | CannotCompileException | NotFoundException e) {
                        e.printStackTrace();
                        IllegalClassFormatException illegalClassFormatException = new IllegalClassFormatException();
                        illegalClassFormatException.initCause(e);
                        throw illegalClassFormatException;
                    }
                }
                return null;
            }

            @Override
            public byte[] transform(Module module, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
                if (className.equals("org/springframework/web/client/RestTemplate")) {
                    ClassPool classPool = ClassPool.getDefault();
                    ByteArrayInputStream stream = new ByteArrayInputStream(classfileBuffer);
                    try {
                        CtClass ctClass = classPool.makeClass(stream);

                        CtConstructor[] constructors = ctClass.getDeclaredConstructors();
                        for (CtConstructor ctConstructor : constructors) {
                            try (BufferedReader br = new BufferedReader(
                                    new InputStreamReader(
                                            Objects.requireNonNull(ClassLoader.getSystemResourceAsStream("bodySource.txt"))))) {

                                StringBuilder sb = new StringBuilder();
                                while (br.ready()) {
                                    sb.append(br.readLine());
                                }

                                ctConstructor.insertBeforeBody(
                                        sb.toString()
                                );

                            }
                        }

                        return ctClass.toBytecode();
                    } catch (IOException | CannotCompileException e) {
                        e.printStackTrace();
                        IllegalClassFormatException illegalClassFormatException = new IllegalClassFormatException();
                        illegalClassFormatException.initCause(e);
                        throw illegalClassFormatException;
                    }
                }
                return null;
            }
        });
    }
}
