/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestTemplateAddonUserSystemProxy;

import javassist.CannotCompileException;
import javassist.ClassPool;
import javassist.CtClass;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.instrument.Instrumentation;
import java.security.ProtectionDomain;

public class RestTemplateRewrite {
    public static void premain(String agentArgs, Instrumentation instrumentation) {
        instrumentation.addTransformer(new ClassFileTransformer() {
            @Override
            public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
                if (className.equals("org/springframework/web/client/RestTemplate")) {
                    ClassPool classPool = ClassPool.getDefault();
                    ByteArrayInputStream stream = new ByteArrayInputStream(classfileBuffer);
                    try {
                        CtClass ctClass = classPool.makeClass(stream);
                        ctClass.instrument(new ClassEditor());
                        return ctClass.toBytecode();
                    } catch (IOException | CannotCompileException e) {
                        e.printStackTrace();
                        IllegalClassFormatException illegalClassFormatException = new IllegalClassFormatException();
                        illegalClassFormatException.initCause(e);
                        throw illegalClassFormatException;
                    }
                }
                return null;
            }

            @Override
            public byte[] transform(Module module, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
                if (className.equals("org/springframework/web/client/RestTemplate")) {
                    ClassPool classPool = ClassPool.getDefault();
                    ByteArrayInputStream stream = new ByteArrayInputStream(classfileBuffer);
                    try {
                        CtClass ctClass = classPool.makeClass(stream);
                        ctClass.instrument(new ClassEditor());
                        return ctClass.toBytecode();
                    } catch (IOException | CannotCompileException e) {
                        e.printStackTrace();
                        IllegalClassFormatException illegalClassFormatException = new IllegalClassFormatException();
                        illegalClassFormatException.initCause(e);
                        throw illegalClassFormatException;
                    }
                }
                return null;
            }
        });
    }
}
